### ISSUE TITLE
Cannot set 'mode' through configuration file

### ISSUE THREAD

**Issue by antoniocambados** [phpmob/ace-bundle#1]
Considering this configuration:

```yaml
# config/packages/phpmob_ace.yaml
phpmob_ace:
    configs:
        html:
            autoScrollEditorIntoView: true
            maxLines: 20
            minLines: 5
            mode: 'ace/mode/html'
            theme: 'ace/theme/github'
```

Used in form type such as:

```php
public function buildForm(FormBuilderInterface $builder, array $options)
{
    $builder
        ->add('html', AceType::class, [
            'required'    => false,
            'config_name' => 'html',
        ])
    ;
}
```

The resulting `mode` used is `null`.
